/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidisciplina;

import disciplina.DisciplinaEspecifica;
import disciplina.NegocioDisciplinaEspecifica;
import guicurso.InserirCurso;
import javax.swing.JOptionPane;

/**
 *
 * @author deyvid
 */
public class InserirDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarDisciplina
     */
    public InserirDisciplina() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTurnoD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTurmaD = new javax.swing.JTextField();
        btnCadastraCurso = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        alterDados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Código Da Disciplina :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 10, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtCodigoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDActionPerformed(evt);
            }
        });
        txtCodigoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCodigoD(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 18, 0, 0);
        jPanel1.add(txtCodigoD, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nome Da Disciplina :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 16, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtNomeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDActionPerformed(evt);
            }
        });
        txtNomeD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeD(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 407;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel1.add(txtNomeD, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Turno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 98, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtTurnoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTurno(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 0);
        jPanel1.add(txtTurnoD, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Turma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 95, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 0);
        jPanel1.add(txtTurmaD, gridBagConstraints);

        btnCadastraCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/book_open.png"))); // NOI18N
        btnCadastraCurso.setText("Cadastrar Disciplina");
        btnCadastraCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraCursoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 117, 0, 0);
        jPanel1.add(btnCadastraCurso, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-faculdade-ibratec.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 129, 0, 142);
        jPanel1.add(jLabel12, gridBagConstraints);

        alterDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/style_edit.png"))); // NOI18N
        alterDados.setText("Alterar Dados");
        alterDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterDadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 117, 87, 0);
        jPanel1.add(alterDados, gridBagConstraints);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/page_white_gear.png"))); // NOI18N
        jMenu3.setText("Opção");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/arrow_redo.png"))); // NOI18N
        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraCursoActionPerformed
        // cadastrar disciplina no sqlServer
        DisciplinaEspecifica d = new DisciplinaEspecifica();
        try {
            if (txtNomeD.getText().equals("") == false) {
                String n = txtNomeD.getText();
            }
            d.setCodigoDisciplina(Integer.parseInt(txtCodigoD.getText()));
            d.setNomeDisciplina(txtNomeD.getText());
            d.setTurma(txtTurmaD.getText());
            d.setTurno(txtTurnoD.getText());

            NegocioDisciplinaEspecifica N = new NegocioDisciplinaEspecifica();
            N.cadastrarDisciplina(d);
            JOptionPane.showMessageDialog(rootPane, "Disciplina inserida no Sistema");

            //jLabel4.setText(String.valueOf(a.getMatricula()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnCadastraCursoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //chama o form cadastraCurso
        InserirCurso cd = new InserirCurso();
        cd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void alterDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterDadosActionPerformed
        //altera dados o aluno
        try {
            DisciplinaEspecifica c = new DisciplinaEspecifica();
            if (txtNomeD.getText().equals("") == false) {
                String n = txtNomeD.getText();
            }

            c.setCodigoDisciplina(Integer.parseInt(txtCodigoD.getText()));
            c.setNomeDisciplina(txtNomeD.getText());
            c.setTurma(txtTurmaD.getText());
            c.setTurno(txtTurnoD.getText());

            NegocioDisciplinaEspecifica N = new NegocioDisciplinaEspecifica();
            N.alterarDisciplina(c);
            JOptionPane.showMessageDialog(rootPane, "dados alterados ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_alterDadosActionPerformed

    private void txtCodigoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDActionPerformed

    private void campoCodigoD(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodigoD
        // restrição  de letras no campo codigo e da quantidade de caracteres
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();

        }

    }//GEN-LAST:event_campoCodigoD

    private void txtNomeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDActionPerformed

    private void campoNomeD(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeD
         //restrição de numero no  campo nome e da quantidade de caracteres
        String caracteres = "0987654321";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_campoNomeD

    private void campoTurno(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTurno
          //restrição de numero no  campo turno e da quantidade de caracteres
        String caracteres = "0987654321";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }else if (txtTurnoD.getText().length() > 4) {
            evt.consume();
        }
    }//GEN-LAST:event_campoTurno

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterDados;
    private javax.swing.JButton btnCadastraCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigoD;
    private javax.swing.JTextField txtNomeD;
    private javax.swing.JTextField txtTurmaD;
    private javax.swing.JTextField txtTurnoD;
    // End of variables declaration//GEN-END:variables
}
